export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';

export const LOAD_CUSTOMERS = 'LOAD_CUSTOMERS';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';

export const LOAD_INVOICES = 'LOAD_INVOICES';

export const ADD_INVOICE_PRODUCT = 'ADD_INVOICE_PRODUCT';
export const CHANGE_INVOICE = 'CHANGE_INVOICE';
export const DELETE_INVOICE_PRODUCT = 'DELETE_INVOICE_PRODUCT';
export const CHANGE_INVOICE_PRODUCT_QTY = 'CHANGE_INVOICE_PRODUCT_QTY';
export const ADD_INVOICE = 'ADD_INVOICE';